# The suit field is hard-coded to 1-4 so suits can be correlated
# This also reflects the order used when giving tarot
SUIT_CHOICES = (
(1, 'Suit 1 (e.g., Wands)'),
(2, 'Suit 2 (e.g., Cups)'),
(3, 'Suit 3 (e.g., Swords)'),
(4, 'Suit 4 (e.g., Pentacles)'))

MAJOR_ARCANA_CHOICES = (
(0, 'The Fool'),
(1, 'The Magician'),    
(2, 'The High Priestess'),    
(3, 'The Empress'),
(4, 'The Emperor'),
(5, 'The Hierophant'),                 
(6, 'The Lovers'),
(7, 'The Chariot'), 
(8, 'Strength'),    
(9, 'The Hermit'),    
(10, 'The Wheel of Fortune'),
(11, 'Justice'),    
(12, 'The Hanged Man'),    
(13, 'Death'),   
(14, 'Temperance'),    
(15, 'The Devil'),    
(16, 'The Tower'),
(17, 'The Star'),    
(18, 'The Moon'),    
(19, 'The Sun'),  
(20, 'Judgement'),    
(21, 'The World'))

MINOR_ARCANA_CHOICES = (
(22, 'Ace of Wands'),
(23, '2 of Wands'),
(24, '3 of Wands'),
(25, '4 of Wands'),
(26, '5 of Wands'),
(27, '6 of Wands'),
(28, '7 of Wands'),
(29, '8 of Wands'),
(30, '9 of Wands'),
(31, '10 of Wands'),
(32, 'Page of Wands'),
(33, 'Knight of Wands'),
(34, 'Queen of Wands'),
(35, 'King of Wands'),

(36, 'Ace of Cups'),
(37, '2 of Cups'),
(38, '3 of Cups'),
(39, '4 of Cups'),
(40, '5 of Cups'),
(41, '6 of Cups'),
(42, '7 of Cups'),
(43, '8 of Cups'),
(44, '9 of Cups'),
(45, '10 of Cups'),
(46, 'Page of Cups'),
(47, 'Knight of Cups'),
(48, 'Queen of Cups'),
(49, 'King of Cups'),

(50, 'Ace of Swords'),
(51, '2 of Swords'),
(52, '3 of Swords'),
(53, '4 of Swords'),
(54, '5 of Swords'),
(55, '6 of Swords'),
(56, '7 of Swords'),
(57, '8 of Swords'),
(58, '9 of Swords'),
(59, '10 of Swords'),
(60, 'Page of Swords'),
(61, 'Knight of Swords'),
(62, 'Queen of Swords'), 
(63, 'King of Swords'),

(64, 'Ace of Pentacles'),
(65, '2 of Pentacles'),
(66, '3 Pentacles'),
(67, '4 of Pentacles'),
(68, '5 of Pentacles'),
(69, '6 of Pentacles'),
(70, '7 of Pentacles'),
(71, '8 of Pentacles'),
(72, '9 of Pentacles'),
(73, '10 of Pentacles'),
(74, 'Page of Pentacles'),
(75, 'Knight of Pentacles'),
(76, 'Queen of Pentacles'),                     
(77, 'King of Pentacles'))

ALL_CARD_CHOICES = MAJOR_ARCANA_CHOICES + MINOR_ARCANA_CHOICES